language: python
python:
  - "2.7"
  - "3.6"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
cache: pip
# command to install dependencies
install:
  - pip install -U setuptools
  - pip install coverage pytest pytest-cov dill
  - pip install Cython --install-option="--no-cython-compile"
  - pip install -e .[plot,glyspace]
  # - pip install -r requirements.txt
# command to run tests
script: make test
